### ISSUE TITLE
could not find alignment reference

### ISSUE THREAD

**Issue by moutusee** [Albacore/albacore#247]
**gave the code**
read_fast5_basecaller.py -i /mmoutusee@moutusee-VirtualBox:~/Desktop/miniconda$ read_fast5_basecaller.py -i /media/sf_clinical_first_fast5_pass -f FLO-MIN106 -k SQK-LSK108 -o fastq -barcoding -t 4 -s /home/moutusee/Desktop/clinical_first_albacore -r

**the following messages I got**
Traceback (most recent call last):
  File "/home/moutusee/.local/bin/read_fast5_basecaller.py", line 479, in <module>
    sys.exit(main(opts, config_override))
  File "/home/moutusee/.local/bin/read_fast5_basecaller.py", line 164, in main
    initialise_aligner(config, opts.align_ref, opts.data_path, 'aligner') + \
  File "/home/moutusee/.local/lib/python3.6/site-packages/albacore/aligner_utils.py", line 146, in initialise_aligner
    raise FileNotFoundError('Could not find alignment reference {}.'.format(alignref))
FileNotFoundError: Could not find alignment reference /home/moutusee/.local/lib/python3.6/site-packages/albacore/data_versioned/rcoding.

**Comment by haf** [comment]
Wrong library.
